formatting:
  # Conflicts with IDEA formatting
  NoWildcardImports:
    active: false

style:
  # Conflicts with IDEA formatting
  WildcardImport:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  ReturnCount:
    excludes:
      - "**/Main.kt" # Complex UI

naming:
  # Useful for exception classes and result data types
  MatchingDeclarationName:
    active: false
